export const DEFAULT_DEVICE_STATUS_LED_BRIGHTNESS_PERCENT = 80;
export const DEFAULT_DEVICE_KEY_LED_BRIGHTNESS_PERCENT = 80;
export const DEFAULT_DEVICE_LED_ZONE_BRIGHTNESS_PERCENT = 100;
export const LEGACY_DEVICE_STATUS_KEY_LED_BRIGHTNESS_DEFAULT_PERCENT = 50;
